### ISSUE TITLE
Is 10 ** -342 minimum possible value for double range in scientific_ method?

### ISSUE THREAD

**Issue by MaxGraey** [jdh8/metallic#4]
It seems this should be `-324` [here](https://github.com/jdh8/metallic/blob/master/src/stdlib/parse/scientific.h#L71)

**Comment by jdh8** [comment]
It is because maximum `significand` is 2<sup>64</sup> &minus; 1, so we need -342 to go small enough. `significand` is interpreted as a plain integer here.

Smallest representable positive `double` &approx; 5e-324
(2<sup>64</sup> &minus; 1) 10<sup>-342</sup> &approx; 2e-323

**Comment by MaxGraey** [comment]
Got it! thanks
